"""Safe managed-block editing for POSIX shell startup files."""

from __future__ import annotations

from pathlib import Path
import shlex
import stat
from typing import Iterable

from .backup import BackupManager
from .errors import ToolError
from .models import ToolConfig
from .storage import atomic_write_text

START = "# >>> termux-tool managed block >>>"
END = "# <<< termux-tool managed block <<<"


def _quoted(value: str) -> str:
    return shlex.quote(value)


def render_block(config: ToolConfig) -> str:
    lines = [
        START,
        "# Generated by termux-tool. Changes outside this block are preserved.",
        f"export TERMUX_TOOL_PROMPT={_quoted(config.prompt)}",
        'PS1="$TERMUX_TOOL_PROMPT"',
        f"printf '%s\\n' {_quoted(config.welcome)}",
    ]
    if config.banner:
        for banner_line in config.banner.splitlines():
            lines.append(f"printf '%s\\n' {_quoted(banner_line)}")
    for name, value in sorted(config.aliases.items()):
        lines.append(f"alias {name}={_quoted(value)}")
    lines.append(END)
    return "\n".join(lines)


def _replace_block(original: str, block: str) -> str:
    start = original.find(START)
    end = original.find(END)
    if start >= 0 and end < start:
        raise ToolError("shell file contains a malformed termux-tool managed block")
    if start >= 0:
        end += len(END)
        updated = original[:start] + block + original[end:]
    else:
        separator = "" if not original or original.endswith("\n") else "\n"
        updated = original + separator + "\n" + block + "\n"
    return updated


def apply(path: Path, config: ToolConfig, backups: BackupManager, create: bool = False) -> bool:
    if path.exists() and not path.is_file():
        raise ToolError(f"shell path is not a regular file: {path}")
    if not path.exists() and not create:
        return False
    original = path.read_text(encoding="utf-8") if path.exists() else ""
    updated = _replace_block(original, render_block(config))
    if updated == original and path.exists():
        return False
    mode = stat.S_IMODE(path.stat().st_mode) if path.exists() else 0o600
    if path.exists():
        backups.create(path)
    atomic_write_text(path, updated, mode=mode)
    return True


def remove(path: Path, backups: BackupManager) -> bool:
    if not path.exists():
        return False
    if not path.is_file():
        raise ToolError(f"shell path is not a regular file: {path}")
    original = path.read_text(encoding="utf-8")
    start = original.find(START)
    end = original.find(END)
    if start < 0 and end < 0:
        return False
    if start < 0 or end < start:
        raise ToolError("shell file contains a malformed termux-tool managed block")
    end += len(END)
    updated = (original[:start].rstrip("\n") + original[end:]).lstrip("\n")
    if original.endswith("\n") and updated and not updated.endswith("\n"):
        updated += "\n"
    mode = stat.S_IMODE(path.stat().st_mode)
    backups.create(path)
    atomic_write_text(path, updated, mode=mode)
    return True
